config/routes.rb
Cheerups::Application.routes.draw do
  devise_for :users, :controllers => {:sessions => "sessions"}

  resources :users, only: [:index, :show]
  get "/launch" => 'main_pages#launch'
  get "/home" => 'main_pages#home'

  root to: "main_pages#launch"
  resources :cheer_ups
  get 'cheer_ups/upvote/:id', to: 'cheer_ups#upvote', as: 'upvote'
  get 'cheer_ups/downvote/:id', to: 'cheer_ups#downvote', as: 'downvote'
  get 'trending', to: 'main_pages#trending', as: 'trending'

end

app/controllers/main_pages_controller.rb
class MainPagesController < ApplicationController

  def home
    @cheer_ups = CheerUp.all
    @user = current_user
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cheer_ups }
    end
  end

  def new
    @Cheer_ups = CheerUp.new
  end

  def launch
  end

  def trending
    @cheer_ups = CheerUp.order("rating DESC").all
    @user = current_user
    render :home
  end


end

app/helpers/main_pages_helper.rb
module MainPagesHelper
end

app/views/main_pages/_cu_feed.html.erb
<% cheer_ups.each do |cheer_up| %>
<div class="cheer_up <%= 'large' if (cheer_up.sound_upload.length + cheer_up.image_upload.length) > 0 %> <%= "user_cheerup" if !(current_user.nil?) && cheer_up.user_id == current_user.id %> ">
  <div>
  <div class="profileimage cf">
      <%= image_tag cheer_up.user.image_upload.thumb.url %>
    </div>
  <div class="profilename cf">
      <%= cheer_up.user.firstname %> <%= cheer_up.user.lastname %>
    </div>
  </div>
  <% if cheer_up.image_upload.length > 0 %>
  <div class="cuimage">
    <%= image_tag cheer_up.image_upload.detail.url %>
  </div>
  <% end %>


  <% if cheer_up.sound_upload.length > 0 %>
  <div class="cusound">
    <audio controls>
      <source src="<%= cheer_up.sound_upload %>" type="audio/ogg">
        <source src="<%= cheer_up.sound_upload %>" type="audio/mpeg">
          Your browser does not support the audio element.
        </audio>
      </div>
      <% end %>

      <div class="cucontent">
        <%= cheer_up.content %>
      </div>
      <div>
        <b>Rating:</b>
        <span data-cheer_up_id_rating=<%= cheer_up.id %>><%= cheer_up.rating %></span>
      </div>

      <% if current_user %>
        <% unless cheer_up.user_id == current_user.id then %>
          <%= link_to image_tag("thumbsup.png"), upvote_path(cheer_up.id), remote: true%>
          <%= link_to image_tag("thumbsdown.png"), downvote_path(cheer_up.id), remote: true%>
        <% end %>
      <% end %>
    </div>
    <% end %>

<style type="text/css">
<% cheer_ups.each do |cheer_up| %>
  .cu_<%=cheer_up.id%> { background: url('<%= asset_path(randomized_background_image) %>') no-repeat fixed; background-size: cover;}
<% end %>
</style>

app/views/main_pages/_form.html.erb
<%= form_for(new_cheerup) do |f| %>
  <% if new_cheerup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(new_cheerup.errors.count, "error") %> prohibited this cheer_up from being saved:</h2>

      <ul>
      <% new_cheerup.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image_upload %>
    <%= f.file_field :image_upload %>
  </div><br>
  <div class="field">
    <%= f.label :sound_upload %>
    <%= f.file_field :sound_upload %>
  </div><br>
  <div class="field">
    <%= f.label :content %>
    <%= f.text_field :content %>
  </div><br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/main_pages/_single_cu.html.erb
<style type="text/css">
  #cu {
    background: url('<%= asset_path(randomized_background_image) %>') no-repeat fixed;
    background-size: 100% 100%;
    width: 480px;
  }
</style>

<% cheer_ups.each do |cheer_up| %>
<div id="cu" class="container">
  <div class="row">
    <div class="span2 profileimage">
      <%= image_tag @cheer_up.user.image_upload.thumb.url %>
    </div>

      <div class="span4 cu2">
        <div class="cuimage">
          <% if @cheer_up.image_upload.length > 0 %>
          <%= image_tag @cheer_up.image_upload.detail.url %>
          <% end %>
        </div>

        <div class="cusound">
          <% if @cheer_up.sound_upload.length > 0 %>
          <audio controls>
          <source src="<%= @cheer_up.sound_upload %>" type="audio/ogg">
          <source src="<%= @cheer_up.sound_upload %>" type="audio/mpeg">
          Your browser does not support the audio element.
          </audio>
          <% end %>
        </div>
        <div class="cucontent">
          <%= @cheer_up.content %>
        </div>
        <div class="curating">
          <b>Rating:</b>
          <span data-cheer_up_id_rating="<%= cheer_up.id %>" ><%= cheer_up.rating %></span>
        </div>

        <% if current_user %>
          <%= link_to 'Edit', edit_cheer_up_path(cheer_up), class: "btn" if cheer_up.user_id == current_user.id %>
          <% unless cheer_up.user_id == current_user.id then %>

            <%= link_to 'up vote', upvote_path(cheer_up.id), class: 'btn', 'data-cheer_up_id' => "#{cheer_up.id}", 'data-href' => upvote_path(cheer_up.id)  %>
            <%= link_to 'down vote', downvote_path(cheer_up.id), class: 'btn', 'data-cheer_up_id' => "#{cheer_up.id}", 'data-href' => downvote_path(cheer_up.id) %>
          <% end %>
        <% end %>
  </div>

</div>
</div>
<% end %>

app/views/main_pages/_trending.js.erb
$("#cu_feed").html("<%= @cheer_ups %>");

app/views/main_pages/home.html.erb
<div id='homepage_container' class='cf'>
  <% if signed_in? %>
  <div class="cf culeft">
    <div class=" biomain">
      <div class="bio cf">
        <%= image_tag @user.image_upload.thumb.url unless @user.image_upload.thumb.url.nil? %>

        <div class='bio_name cf'><%= @user.firstname %> <%= @user.lastname %></div>
      </div>
      <div class="content">
        <%= @user.bio %>
        <h4><%= current_user.overall_rating %></h4>
      </div>

      <a class="btn btn-large btn-block btn-primary" data-toggle="collapse" data-target="#demo">
        Edit Your Profile!
      </a>
      <div id="demo" class="collapse">

        <%= form_for(@user, :as => resource_name, :url => users_path, :html => { :method => :put }) do |f| %>
        <%= devise_error_messages! %>

        <div class="field"><%= f.label :email %>
          <%= f.email_field :email, :autofocus => true, :placeholder => "Email", required: "required" %></div>

          <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
          <div>Currently waiting confirmation for: <%= resource.unconfirmed_email %></div>
          <% end %>

          <div class="field">
            <%= f.label :firstname %>
            <%= f.text_field :firstname, :placeholder => "Firstname", required: "required" %>
          </div>
          <div class="field">
            <%= f.label :lastname %>
            <%= f.text_field :lastname, :placeholder => "Lastname", required: "required" %>
          </div>
          <div class="field">
            <%= f.label :image_upload %>
            <%= f.file_field :image_upload, required: "required" %>
          </div>
          <div class="field">
            Remove Image
            <%= f.check_box :remove_image_upload %>
          </div>
          <div class="field">
            <%= f.label :bio %>
            <%= f.text_area :bio, :placeholder => "BIO", required: "required" %>
          </div>


          <div class="field"><%= f.label :password %> <i>(leave blank if you don't want to change it)</i>
            <%= f.password_field :password, :autocomplete => "off" %></div>

            <div class="field"><%= f.label :password_confirmation %>
              <%= f.password_field :password_confirmation %></div>

              <div class="field"><%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i>
                <%= f.password_field :current_password, :placeholder => "Current Password", required: "required" %></div>

                <div><%= f.submit "Update" %></div>
                <% end %>

                <h3>Cancel my account</h3>

                <p>Unhappy? <%= button_to "Cancel my account", registration_path(resource_name), :data => { :confirm => "Are you sure?" }, :method => :delete %></p>

                <%= link_to "Back", :back %>

              </div>
            </div>
            <!--insert the form here -->


            <a class="btn btn-large btn-block btn-primary" data-toggle="collapse" data-target="#democheerup">
             Create a Cheerup!
           </a>

           <div id="democheerup" class="collapse">
            <%= render partial: "form", locals: {new_cheerup: CheerUp.new}  %>
          </div>
        </div>
        <% end %>

        <div class="cf curight">
          <div class="cu_feed_options filter option-set btn-group cf" data-filter-group="category" >
            <a href="#" data-filter-value=""><button type="button" class="btn btn-info">Global</button></a>
            <% unless current_user.nil? %>
            <a href="#" data-filter-value=".user_cheerup"><button type="button" class="btn btn-info">Yours</button></a>
            <% end %>
          </div>


          <div id='cu_feed' >
            <%= render partial: 'cu_feed', locals: {cheer_ups: @cheer_ups}  %>
          </div>

        </div>

      </div>

app/views/main_pages/launch.html.erb
<div class="launch_container">
  <div class="launch_div_one">
    <div class="launch_one_left" >
      <h1>Get happy with Cheerup!</h1>
        <p>
          Chase the blues away with the Cheerup app.  Members create and share content that makes makes us happy.<br><br>
          Hey!!! Hey you!!! Do you have any food!?!?! Woof!! Bark!!! Grr!!!
        </p>
    </div>
    <div class="launch_one_right">
      <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
        <%= devise_error_messages! %>
        <%= f.label :email, class: "form_label"  %>
        <%= f.email_field :email, :autofocus => true, :placeholder => "Email", required: "required" %>
        <%= f.label :password, class: "form_label" %>
        <%= f.password_field :password, :placeholder => "Password", required: "required" %>
        <%= f.label :password_confirm, class: "form_label" %>
        <%= f.password_field :password_confirmation, :placeholder => "Password Confirm", required: "required" %><br>
        <%= f.submit :GO!, class: "btn btn-large btn-success" %>
      <% end %>
    </div><!--launch_one_right-->
  </div><!--launch_one_top-->
  <div class="launch_div_two"></div></div>
  <div class="launch_div_three"></div>
  <div id="ya" class="launch_div_four"></div>
  <div class="launch_div_five"></div>
  <div class="launch_div_six"></div>
  <div class="launch_div_seven"></div>

</div><!--Launch Container-->