config/routes.rb
Cheerups::Application.routes.draw do
  devise_for :users, :controllers => {:sessions => "sessions"}

  resources :users, only: [:index, :show]
  get "/launch" => 'main_pages#launch'
  get "/home" => 'main_pages#home'

  root to: "main_pages#launch"
  resources :cheer_ups
  get 'cheer_ups/upvote/:id', to: 'cheer_ups#upvote', as: 'upvote'
  get 'cheer_ups/downvote/:id', to: 'cheer_ups#downvote', as: 'downvote'
  get 'trending', to: 'main_pages#trending', as: 'trending'

end

app/models/cheer_up.rb
class CheerUp < ActiveRecord::Base

  require 'carrierwave/processing/rmagick'
  mount_uploader :image_upload, AvatarUploader
  mount_uploader :sound_upload, CheersoundUploader

  attr_accessible :content, :image_upload, :latitude, :longitude, :rating, :sound_upload, :user_id

  acts_as_votable

  belongs_to :user

  validates :content, presence: true,length: { maximum: 141 }

  scope :blurb, -> { select("id, content, image_upload, rating, sound_upload, user_id") }

  scope :with_user, -> { includes(:user)}
  scope :with_votes, -> { includes(:votes)}

  def vote_up(user)
    self.liked_by user
    calc_rating
    self.save
  end

  def vote_down(user)
    self.downvote_from user
    calc_rating
    self.save
  end

  def calc_rating
    self.rating = upvotes.size - downvotes.size
  end

  # def rating
  #   upvotes.size - downvotes.size
  # end


end

app/controllers/cheer_ups_controller.rb
class CheerUpsController < ApplicationController
  # GET /cheer_ups
  # GET /cheer_ups.json

  load_and_authorize_resource

  def index
    @cheer_ups = CheerUp.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cheer_ups }
    end
  end

  # GET /cheer_ups/1
  # GET /cheer_ups/1.json
  def show
    @cheer_up = CheerUp.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cheer_up }
    end
  end

  # GET /cheer_ups/new
  # GET /cheer_ups/new.json
  def new
    @cheer_up = CheerUp.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cheer_up }
    end
  end

  # GET /cheer_ups/1/edit
  def edit
    @cheer_up = CheerUp.find(params[:id])
  end

  # POST /cheer_ups
  # POST /cheer_ups.json
  def create
    params[:cheer_up][:user_id] = current_user.id
    @cheer_up = CheerUp.new(params[:cheer_up])
    respond_to do |format|
      if @cheer_up.save
        format.html { redirect_to home_path, notice: 'Cheer up was successfully created.' }
        format.json { render json: @cheer_up, status: :created, location: @cheer_up }
      else
        format.html { render action: "new" }
        format.json { render json: @cheer_up.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cheer_ups/1
  # PUT /cheer_ups/1.json
  def update
    @cheer_up = CheerUp.find(params[:id])

    respond_to do |format|
      if @cheer_up.update_attributes(params[:cheer_up])
        format.html { redirect_to @cheer_up, notice: 'Cheer up was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cheer_up.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cheer_ups/1
  # DELETE /cheer_ups/1.json
  def destroy
    @cheer_up = CheerUp.find(params[:id])
    @cheer_up.destroy

    respond_to do |format|
      format.html { redirect_to cheer_ups_url }
      format.json { head :no_content }
    end
  end

  def upvote
    cheer_up = CheerUp.find(params[:id])
    cheer_up.vote_up(current_user)
    respond_to do |format|
      format.html { redirect_to(home_path) }
      format.js { }
      format.json { head :no_content }
    end

    # redirect_to request.referer
  end

  def downvote
    cheer_up = CheerUp.find(params[:id])
    cheer_up.vote_down(current_user)
    respond_to do |format|
      format.html { redirect_to(home_path) }
      format.js { }
      format.json { head :no_content }
    end
    # redirect_to request.referer
  end
end

app/helpers/cheer_ups_helper.rb
module CheerUpsHelper
end

app/views/cheer_ups/_form.html.erb
<%= form_for(@cheer_up) do |f| %>
  <% if @cheer_up.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cheer_up.errors.count, "error") %> prohibited this cheer_up from being saved:</h2>

      <ul>
      <% @cheer_up.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image_upload %><br />
    <%= f.file_field :image_upload %>
  </div>
  <div class="field">
    <%= f.label :sound_upload %><br />
    <%= f.file_field :sound_upload %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cheer_ups/_single_cu.html.erb
<% cheer_ups.each do |cheer_up| %>
<div id="cu" class="container cheer_up row">
<!--     <div class="span2 profileimage">
      <%= image_tag cheer_up.user.image_upload.thumb.url %>
    </div>
 -->
      <div class="span4 cu2">
        <div class="cuimage">
          <% if cheer_up.image_upload.length > 0 %>
          <%= image_tag cheer_up.image_upload.detail.url %>
          <% end %>
        </div>

        <div class="cusound">
          <% if cheer_up.sound_upload.length > 0 %>
          <audio controls>
          <source src="<%= cheer_up.sound_upload %>" type="audio/ogg">
          <source src="<%= cheer_up.sound_upload %>" type="audio/mpeg">
          Your browser does not support the audio element.
          </audio>
          <% end %>
        </div>
        <div class="cucontent">
          <%= cheer_up.content %>
        </div>
        <div class="curating">
          <b>Rating:</b>
          <%= cheer_up.rating %>
        </div>

        <%= link_to 'Edit', edit_cheer_up_path(cheer_up), class: "btn" %> |
        <%= link_to 'Back', cheer_ups_path, class: "btn" %>
        <%= link_to 'up vote', upvote_path(cheer_up.id), class: 'btn' %>
        <%= link_to 'down vote', downvote_path(cheer_up.id), class: 'btn' %>
  </div>

</div>
<% end %>

app/views/cheer_ups/downvote.js.erb
$("span[data-cheer_up_id_rating=<%= @cheer_up.id %>]").html("<%= @cheer_up.rating %>");

app/views/cheer_ups/edit.html.erb
<h1>Editing cheer_up</h1>

<%= render 'form' %>

<%= link_to 'Show', @cheer_up %> |
<%= link_to 'Back', cheer_ups_path %>

app/views/cheer_ups/index.html.erb
<h1>Listing cheer_ups</h1>

<table>
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Image</th>
    <th>CheerUp!</th>
    <th>Sound</th>
    <th>Rating</th>
    <th>Votes</th>

    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cheer_ups.each do |cheer_up| %>
  <tr>
    <td><%= cheer_up.user.firstname %></td>
    <td><%= cheer_up.user.lastname %></td>
    <td><%= image_tag cheer_up.image_upload.thumb.url unless cheer_up.image_upload.thumb.url.nil? %></td>
     <td><%= cheer_up.content %></td>
    <td><%= cheer_up.sound_upload %></td>
    <td><%= cheer_up.rating %></td>
    <td><%= cheer_up.votes.size %></td>
    <td><%= link_to 'Show', cheer_up %></td>
    <td><%= link_to 'Edit', edit_cheer_up_path(cheer_up) %></td>
    <td><%= link_to 'Destroy', cheer_up, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cheer up', new_cheer_up_path %>

app/views/cheer_ups/new.html.erb
<h1>Add a Cheer Up :D</h1>

<%= render 'main_pages/form', new_cheerup: CheerUp.new %>

<%= link_to 'Back', cheer_ups_path %>

app/views/cheer_ups/show.html.erb
<style type="text/css">
  #cu {
    background: url('<%= asset_path(randomized_background_image) %>') no-repeat fixed;
    background-size: 100% 100%;
    width: 480px;
  }
</style>

<p id="notice"><%= notice %></p>

<div id="cu" class="container">
  <div class="row">
    <div class="span2 profileimage">
      <%= image_tag @cheer_up.user.image_upload.thumb.url %>
    </div>

      <div class="span4 cu2">
        <div class="cuimage">
          <% if @cheer_up.image_upload.length > 0 %>
          <%= image_tag @cheer_up.image_upload.detail.url %>
          <% end %>
        </div>

        <div class="cusound">
          <% if @cheer_up.sound_upload.length > 0 %>
          <audio controls>
          <source src="<%= @cheer_up.sound_upload %>" type="audio/ogg">
          <source src="<%= @cheer_up.sound_upload %>" type="audio/mpeg">
          Your browser does not support the audio element.
          </audio>
          <% end %>
        </div>
        <div class="cucontent">
          <%= @cheer_up.content %>
        </div>
        <div class="curating">
          <b>Rating:</b>
          <%= @cheer_up.rating %>
        </div>

        <%= link_to 'Edit', edit_cheer_up_path(@cheer_up), class: "btn" %> |
        <%= link_to 'Back', cheer_ups_path, class: "btn" %>
        <%= link_to 'up vote', upvote_path(@cheer_up.id), class: 'btn' %>
        <%= link_to 'down vote', downvote_path(@cheer_up.id), class: 'btn' %>
  </div>

</div>

app/views/cheer_ups/upvote.js.erb
$("span[data-cheer_up_id_rating=<%= @cheer_up.id %>]").html("<%= @cheer_up.rating %>");