config/routes.rb
Cheerups::Application.routes.draw do
  devise_for :users, :controllers => {:sessions => "sessions"}

  resources :users, only: [:index, :show]
  get "/launch" => 'main_pages#launch'
  get "/home" => 'main_pages#home'

  root to: "main_pages#launch"
  resources :cheer_ups
  get 'cheer_ups/upvote/:id', to: 'cheer_ups#upvote', as: 'upvote'
  get 'cheer_ups/downvote/:id', to: 'cheer_ups#downvote', as: 'downvote'
  get 'trending', to: 'main_pages#trending', as: 'trending'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cheerups</title>
  <link href='http://fonts.googleapis.com/css?family=Shadows+Into+Light+Two' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

    <div class="navbar navbar-inverse navmarg">
      <div class="navbar-inner">
        <a class="brand" href="/">Cheer Up!</a>
        <ul class="nav">
          <li class="divider-vertical"></li>
          <li><%= link_to('Home', home_path) %></li>
          <li><%= link_to 'Trending', trending_path %></li>
         </ul>
        <div class="pull-right">
          <ul class="nav">
            <li class='narrow_only'><%= link_to('Add new', new_cheer_up_path)%></li>
          </ul>
          <% if current_user %>
            <%= image_tag current_user.image_upload.thumb.url %>
            <%= link_to "log out", destroy_user_session_path, method: :delete, class: 'btn btn-danger' %>
          <% else %>
          <%= form_for("user", :url => user_session_path) do |f| %>
          <%= f.email_field :email, :placeholder => "Email", required: "required" %>
          <%= f.password_field :password, :placeholder => "Password", required: "required" %>
          <%= f.submit 'Sign in', class: 'btn btn-success' %>
          <%= link_to "Forgot your password?", new_password_path('user') %>
          <%= f.check_box :remember_me %>
          <%= f.label :remember_me %>
          <% end %>
          <% end %>
        </div><!--pull-right-->
      </div><!--navbar-->
    </div>


    <%= yield %>

</body>
</html>